"use client";

import { Provider } from "react-redux";
import { appStore } from "./store";
import List from "../components/List";
import Details from "../components/Details";
import Search from "../components/Search";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={appStore}>
          <Search />
          <List />

          {children}
        </Provider>
      </body>
    </html>
  );
}
